# syntax=docker/dockerfile:1

# * https://gallery.ecr.aws/lambda/nodejs
FROM public.ecr.aws/lambda/nodejs:20

WORKDIR $LAMBDA_TASK_ROOT

COPY . .

# * Give AWS permission to access directories and run files.
# * https://repost.aws/knowledge-center/lambda-deployment-package-errors
RUN \
	dnf --assumeyes install findutils && \
	npm ci && \
	find . -type d -exec chmod 755 {} \; && \
	find . -type f -exec chmod 644 {} \; && \
	dnf --assumeyes remove findutils

CMD [ "index.handler" ]
