# syntax=docker/dockerfile:1

# * https://gallery.ecr.aws/lambda/nodejs
FROM public.ecr.aws/lambda/nodejs:20

WORKDIR $LAMBDA_TASK_ROOT

COPY package*.json ./

RUN [ -f package-lock.json ] && npm clean-install || echo "Skipped: no package-lock.json file found"

RUN \
	npm install --global \
		@1mill/sops@^0.0.8 \
		@1mill/with-iota@^0.2.1 \
	&& npm link \
		@1mill/sops \
		@1mill/with-iota

COPY . .

# * Give AWS permission to access directories and run files.
# * https://repost.aws/knowledge-center/lambda-deployment-package-errors
RUN \
	dnf --assumeyes install findutils && \
	find . -type d -exec chmod 755 {} \; && \
	find . -type f -exec chmod 644 {} \; && \
	dnf --assumeyes remove findutils

CMD [ "index.handler" ]
